Trecker/Trecker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Trecker/task/urls.py
from django.urls import path, include
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='task-list'),
    path('task/<int:pk>/', views.TaskDetailViews.as_view(), name='task-detail'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name='task-update'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='task-delete'),
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('register/', views.register_view, name='register'),
]

Trecker/task/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    STATUS_CHOICES = [
        ('todo', 'To Do'),
        ('inprogres', 'In Progress'),
        ('done', 'Done'),
    ]

    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ]


    title = models.CharField(max_length=511)
    description = models.TextField()
    status = models.CharField(max_length=31, choices=STATUS_CHOICES, default='todo')
    priority = models.CharField(max_length=31, choices=PRIORITY_CHOICES, default='medium')
    due_date = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')

class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    content = models.TextField()
    created_at = models.DateTimeField(null=True, blank=True)
    media = models.FileField(upload_to='comments_media/', blank=True, null=True)

Trecker/task/forms.py
from django import forms
from task.models import Task, Comment

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'title','description', 'status', 'priority', 'due_date', 'user'
        ]

class TaskFilterForm(forms.Form):
    STATUS_CHOICES = [
        ('', 'All'),
        ('todo', 'To Do'),
        ('inprogres', 'In Progress'),
        ('done', 'Done'),
    ]
    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, label='status')

    def __init__(self, *args, **kwargs):
        super(TaskFilterForm, self).__init__(*args, **kwargs)
        self.fields["status"].widget.attrs.update({"class": "form-control"})

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'media']
        widgets = {
            'media': forms.FileInput()
        }

Trecker/task/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from . import models
from . forms import TaskForm, TaskFilterForm, CommentForm
from task.mixins import UserIsOwnerMixin
from django.contrib.auth.decorators import login_required

class TaskListView(LoginRequiredMixin, ListView):
    model = models.Task
    context_object_name = 'tasks'
    template_name = 'task/task_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = models.Task.objects.filter(user=user)
        status = self.request.GET.get('status', '')
        if status:
            queryset = queryset.filter(status=status)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TaskFilterForm(self.request.GET)
        return context


class TaskDetailViews(DetailView):
    model = models.Task
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['comment_form'] = CommentForm()
        return context
    
    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST, request.FILES)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.task = self.get_object()
            comment.save()
            return redirect('task:task-detail', pk=comment.task.pk)

class TaskCreateView(CreateView):
    model = models.Task
    form_class = TaskForm
    success_url = reverse_lazy('task:task-list')
    template_name = 'task/task_create.html'

class TaskUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = models.Task
    form_class = TaskForm
    success_url = reverse_lazy('task:task-list')
    template_name = 'task/task_update.html'

class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Task
    success_url = reverse_lazy('task:task-list')


def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('task:task-list')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'task/login.html')

def custom_logout(request):
    logout(request)
    return redirect('task:task-list') 

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('task:task-list') 
    else:
        form = UserCreationForm()
    return render(request, 'task/register.html', {'form': form})

Trecker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Task Trecker</title>
    <link rel="icon" href="{% static 'img/icon_3.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;600&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Oswald', sans-serif;
        }
    </style>
</head>
<body>
    {% block content %}

    

    {% endblock content %}
</body>
</html>

Trecker/templates/task/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="form-container">
    <div class="container">
        <input type="checkbox" id="register_toggle">
        <div class="slider">
        <form class="form" method="post" action="{% url 'task:login' %}">
            {% csrf_token %}
            <span class="title">Login</span>
            <div class="form_control">
                <input type="text" class="input" name="username" required="">
                <label class="label">Username</label>
            </div>
            <div class="form_control">
                <input type="password" class="input" name="password" required="">
                <label class="label">Password</label>
            </div>
            <button type="submit">Login</button>
            <span class="bottom_text">Don't have an account? <label for="register_toggle" class="swtich">Sign Up</label> </span>
        </form>
        <form class="form" method="POST" action="{% url 'task:register' %}">
            {% csrf_token %}
            <span class="title">Sign Up</span>
            <div class="form_control">
            <input type="text" class="input" required="">
            <label class="label">Username</label>
            </div>
            <div class="form_control">
            <input type="email" class="input" required="">
            <label class="label">Email</label>
            </div>
            <div class="form_control">
            <input type="password" class="input" required="">
            <label class="label">Password</label>
            </div>
            <button>Sign Up</button>
    
            <span class="bottom_text">Already have an account? <label for="register_toggle" class="swtich">Sign In</label> </span>
        </form>
    
        
        </div>
    </div>
</div>
</body>
</html>

Trecker/templates/task/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
{% endblock %}

Trecker/templates/task/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
</head>
<body>
{% block content %}
<div class="container">
    <h2>Видалення завдання</h2>
    <p>Ви впевнені, що хочете видалити завдання "{{ object.title }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Так, видалити</button>
        <a href="{% url 'task:task-list' %}" class="btn btn-secondary">Ні, повернутися до списку завдань</a>
    </form>
</div>
{% endblock %}
</body>
</html>

Trecker/templates/task/task_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Tracker</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/create_task.css' %}">
</head>
<body>  
{% block content %}
<a href="/" class="home-button"><img src="{% static 'img/arrow_2.png' %}" alt="Not Found"></a>
<div class="container mt-5">
    <h2>{{ view.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-3">Зберегти</button>
    </form>
</div>
{% endblock %}
</body>
</html>

Trecker/templates/task/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Tracker</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/task_detail.css' %}">
</head>
<body>  
    {% block content %}
    {% load custom_tags %}
<a href="/" class="home-button"><img src="{% static 'img/arrow_2.png' %}" alt="Not Found"></a>
<div class="container_2 mt-5">
    <!-- Карточка задачи -->
    <div class="card shadow-sm mb-4">
        <div class="card-body">
            <h2 class="card-title text-center display-4">{{ task.title }}</h2>
            <p class="card-text lead">{{ task.description }}</p>
            <p class="mb-2"><strong>Статус:</strong> <span class="badge badge-primary">{{ task.status }}</span></p>
            <p class="mb-4"><strong>Пріоритет:</strong> <span class="badge badge-secondary">{{ task.priority }}</span></p>
            
            <!-- Кнопки обновления и удаления -->
            <div class="d-flex justify-content-end">
                <a href="{% url 'task:task-update' task.id %}" class="btn btn-warning" style="text-decoration: none;">Обновити задачу</a>
                <form action="{% url 'task:task-delete' task.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Ви впевнені, що хочете видалити цю задачу?');">Видалити задачу</button>
                </form>
            </div>
        </div>
    </div>
    <!-- Коментарі -->
    <div class="comments mt-5">
        <h3 class="text-muted">Коментарі</h3>
        <div class="row">
            {% for comment in task.comments.all %}
            <div class="col-12 col-md-6">
                <div class="comment-card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ comment.content }}</p>
                        {% if comment.media %}
                        <div class="media-content my-3">
                            {% if comment.media.url|endswith:".jpg" or comment.media.url|endswith:".png" or comment.media.url|endswith:".jpeg" %}
                            <img src="{{ comment.media.url }}" alt="Зображення коментаря" class="img-fluid rounded">
                            {% elif comment.media.url|endswith:".mp4" %}
                            <video class="video-fluid rounded" controls style="width: 100%;">
                                <source src="{{ comment.media.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                            {% else %}
                            <a href="{{ comment.media.url }}" class="btn btn-link">Завантажити файл</a>
                            {% endif %}
                        </div>
                        {% endif %}
                        <small class="text-muted">Автор: {{ comment.author.username }}</small>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-muted">Коментарі відсутні.</p>
            {% endfor %}
        </div>
    </div>
    
    <!-- Форма додавання коментаря -->
    <div class="add-comment mt-5">
        <div class="card shadow-sm">
            <div class="card-body">
                <h4 class="card-title">Додати коментар</h4>
                <form action="{% url 'task:task-detail' task.id %}" method="post" enctype="multipart/form-data" class="mt-3">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit" class="btn btn-primary">Відправити</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

Trecker/templates/task/task_form.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>dfgfd</title>
    <style>

    </style>
</head>
<body>  
{% block content %}
<div class="container mt-3">
    <h2>{{ view.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Зберегти</button>
    </form>
</div>
{% endblock %}

Trecker/templates/task/task_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="background">
    <div class="container">
        <header class="navbar">
            <img class="icon" src="{% static 'img/icon_3.png' %}" alt="Not Found" style="width: 50px; height: 50px; margin-left: 15px">
            <a href="/" class="navbar-brand">
                <h1>Task Trecker</h1>
            </a>
            <nav>
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'task:task-create' %}" class="nav-link">Create Task</a></li>
                        <li class="nav-item"><a href="{% url 'task:logout' %}" class="nav-link">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'task:login' %}" class="nav-link">Login</a></li>
                        <li class="nav-item"><a href="{% url 'task:register' %}" class="nav-link">Register</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
    </div>

    <h2 class="text-center">Task List</h2>

    <div class="task-cards">
        {% for task in tasks %}
            <div class="task-card">
                <h3><a class="task-title" href="{% url 'task:task-detail' task.pk %}">{{ task.title }}</a></h3>
                <p class="task-status"><strong>Status:</strong> {{ task.status }}</p>
                <a href="{% url 'task:task-delete' task.pk %}">
                    <img src="{% static 'img/tick.png' %}" alt="Delete Task" class="delete-icon">
                </a>
            </div>
        {% empty %}
            <p>No tasks found.</p>
        {% endfor %}
    </div>

    <form method="get" class="filter-form">
        {{ form.as_p }}
        <button type="submit" class="task-button">Filter</button>
    </form>
</div>

<div class="bottom-navbar">
    <p >Copyright © 2024</p>
</div>
{% endblock %}

Trecker/templates/task/task_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
</head>
<body>
{% block content %}
<div class="container mt-5">
    <h2 style="text-align: center;">Update Task</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}
</body>
</html>